version: '3'
services:
  web:
    container_name: webapp-frontend
    build: .
    ports:
      - "5000:5000"
  neo4j:
    container_name: neo4j
    image: "neo4j:latest"
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474" # HTTP
      - "7473:7473" # HTTPS
      - "7687:7687" # Bolt